### ISSUE TITLE
我在做一个基于telegram的新闻频道聚合

### ISSUE THREAD

**Issue by Z-fly** [shoaky009/source-downloader#4]
如何使用本项目爬取一些频道的内容

https://t.me/AI_News_CN
https://t.me/TestFlightCN
https://t.me/xhqcankao

**Comment by shoaky009** [comment]
需求描述不是很具体，另外本项目是针对文件下载和路径管理为主的

**Comment by Z-fly** [comment]
![image](https://github.com/shoaky009/source-downloader/assets/10470892/22f846b8-3580-457a-bb67-431e38e9026f)
直接把SourceItem当作要下载的目标，是不是可以
![image](https://github.com/shoaky009/source-downloader/assets/10470892/96e00781-d1c5-4ecc-bd6a-6bf0837decd3)
例如我要把这个条目爬下来保存到Markdown

**Comment by shoaky009** [comment]
> ![image](https://private-user-images.githubusercontent.com/10470892/296906936-22f846b8-3580-457a-bb67-431e38e9026f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODEyMTEsIm5iZiI6MTcwNTM4MDkxMSwicGF0aCI6Ii8xMDQ3MDg5Mi8yOTY5MDY5MzYtMjJmODQ2YjgtMzU4MC00NTdhLWJiNjctNDMxZTM4ZTkwMjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NDI5NGJmY2NmODFhZmY5MjAxNDZiZDdkMGVkODJkMTI3NjFhMzUzOGQzNzA1YWViZDYzNTNmNGRjYmI0NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UvliH3pCYW-Bu-iby1AIL5NFu8T8iFR4n_u1u1xcXUk) 直接把SourceItem当作要下载的目标，是不是可以 ![image](https://private-user-images.githubusercontent.com/10470892/296907271-96e00781-d1c5-4ecc-bd6a-6bf0837decd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODEyMTEsIm5iZiI6MTcwNTM4MDkxMSwicGF0aCI6Ii8xMDQ3MDg5Mi8yOTY5MDcyNzEtOTZlMDA3ODEtZDFjNS00ZWNjLWJkNmEtNmJmMDgzN2RlY2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYTFmNDAxY2I3NmEyOWZlYmU3MjI0NWI5NGZjMmM3Mjc1N2M2OTlhNDU0ODk1ZmQwMzgyYmE4MzkzNmIxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gk407lUq9DYHPJ47c-drbbqcttdBI9ESQxeqF0ooBWs) 例如我要把这个条目爬下来保存到Markdown

可以不过我要研究一下文本消息根据entities添加上Markdown的语法

**Comment by shoaky009** [comment]
已经添加完了，消息文本样式化的是AI生成的试了一下没什么大问题，拉取该镜像shoaky009/source-downloader:test，然后参考以下配置

```yaml
instances:
  - name: telegram-client
    props:
      api-id: yours
      api-hash: yours
      metadata-path: /app/data/telegram
      proxy: yours
      reconnection-interval: 1
      ping-interval: 30

components:
  source:
    - name: news
      type: telegram
      props:
        client: telegram-client
        include-non-media: true
        chats:
          - chat-id: "-1809784088"
  downloader:
    - name: news
      type: telegram
      props:
        client: telegram-client
        download-path: /downloads
  trigger:
    - name: 20min
      type: fixed
      props:
        interval: PT20M
  item-file-resolver:
    - name: news
      type: telegram

processors:
  - name: telegram-news
    triggers:
      - "fixed:20min"
    source: telegram:news
    downloader: telegram:news
    item-file-resolver: telegram:news
    file-mover: general
    save-path: /telegram/news
    options:
      save-path-pattern: "{item.attrs.chatName}"
      item-expression-inclusions:
        - "item.contentType == 'message'"
      pointer-batch-mode: false
```
