### ISSUE TITLE
如何下载多个频道的？

### ISSUE THREAD

**Issue by Z-fly** [shoaky009/source-downloader#5]
![image](https://github.com/shoaky009/source-downloader/assets/10470892/8fb6274f-e095-4c47-8138-f75f74a73c5c)
这样写无法生效

顺便问下如何控制下载范围 比如从1月1号的消息开始下

**Comment by shoaky009** [comment]
配置变更后要重新加载，可以使用以下API
```bash
方法1:重新加载所有
curl host:port/api/application/reload

方法2:重新加载组件后再加载处理器
curl host:port/api/component/source/telegram/news/reload
curl host:port/api/processor/telegram-new/reload
```

`TelegramSource`目前的实现是第一个频道到达最新的消息才会接着下一个


设置频道起始日期
```yaml
components:
  source:
    - name: news
      type: telegram
      props:
        client: telegram-client
        chats:
          - chat-id: "1111"
            begin-date: "2024-01-01"
          - chat-id: "2222"
```
